name: Build Container Image
on:
  workflow_dispatch:  # 手動実行ボタンを追加
  push:
    branches: [main]
    paths: ['**']

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v4
      - name: initialize before build
        uses: docker/setup-buildx-action@v3
      - name: docker login
        uses: docker/login-action@v3
        with:
          registry: index.docker.io
          username: matildatila
          password: ${{ secrets.DOCKER_REGISTRY_TOKEN }}
      - name: create metadata
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: index.docker.io/matildatilda/hello_docker
          tags: |
            type=raw,value=1.0
            type=sha,prefix=,suffix=,format=short
      - name: build and push
        uses: docker/build-push-action@v5
        with:
          file: ./docker/Dockerfile
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}