name: Build Container Image
on:
  workflow_dispatch:  # 手動実行ボタンを追加
  push:
    branches: [main]
    paths: ['**']

jobs:
  pull-and-run:
    runs-on: ubuntu-latest
    container:
      image: docker.io/matildatilda/hello_docker:1.0
    steps:
      - name: docker login
        uses: docker/login-action@v3
        with:
          username: matildatilda
          password: ${{ secrets.DOCKER_REGISTRY_TOKEN }}
      - name: pull image
        run: docker pull matildatilda/hello_docker:1.0
      - name: run image
        run: docker run --rm matildatilda/hello_docker:1.0